// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decode(arg1, arg2) {
  return window['go']['main']['App']['Decode'](arg1, arg2);
}

export function Encode(arg1, arg2) {
  return window['go']['main']['App']['Encode'](arg1, arg2);
}
